version: "3.8"
services:
  cellxgene_gateway:
    conainter_name: cellxgene_gateway
    build: 
      context: .
    environment:
      - CELLXGENE_LOCATION=cellxgene
      - CELLXGENE_DATA=/h5ad
      - CELLXGENE_PORT=10001
      - GATEWAY_ENABLE_ANNOTATIONS=1
    ports:
      - 10001:10001
    expose:
      - 10001 
    volumes:
      - "./test:/h5ad:z"



